### ISSUE TITLE
Modules: Redundant dependencies

### ISSUE THREAD

**Issue by youwuyou** [PTsolvers/FastIce.jl#45]
Under [Project.toml](https://github.com/PTsolvers/FastIce.jl/blob/276850b6de7b5ebe0dd7887e7a537d8840dd2051/Project.toml#L6-L18), it seems like `GeometryBasics`, `ElasticArrays` and `Preferences` packages are not being used right now in `FastIce.jl`.

**Comment by utkinis** [comment]
Thanks for checking this @youwuyou ! Some of these packages are indeed leftovers from previous experiments in FastIce. `GeometryBasics` will be needed when #44 is merged, other things are redundant.

**Comment by youwuyou** [comment]
@utkinis It seems like #44 has been merged, shall we remove these dependencies in an upcoming pull request?

**Comment by luraess** [comment]
Current working and to be merged branch is `iu/chmy`. Can you check the status there? We can address remaining in there and close it then.

**Comment by luraess** [comment]
Closing this as addressed by #54
